import type { Season } from "@prisma/client";

import { getAffixByName } from "./affixes";
import { ExpansionEnum } from "./expansions";

export enum SeasonId {
  LEGION_7_2_0 = 1,
  LEGION_7_2_5 = 2,
  LEGION_7_3_0 = 3,
  LEGION_7_3_2 = 4,
  LEGION_POST_SEASON = 5,
  BFA_PRE_SEASON = 6,
  BFA_SEASON_1 = 7,
  BFA_SEASON_2 = 8,
  BFA_POST_SEASON_2 = 9,
  BFA_SEASON_3 = 10,
  BFA_POST_SEASON_3 = 11,
  BFA_SEASON_4 = 12,
  BFA_POST_SEASON_4 = 13,
  SL_SEASON_1 = 14,
}

// via https://raider.io/api#/mythic_plus/getApiV1MythicplusStaticdata
export const seasons: (Season & { seasonId: SeasonId })[] = [
  // Legion
  {
    slug: "legion-7.2.0",
    name: "Season 7.2",
    expansionId: ExpansionEnum.LEGION,
    startTime: new Date(0),
    endTime: new Date(1),
    affixId: null,
    seasonId: SeasonId.LEGION_7_2_0,
  },
  {
    slug: "legion-7.2.5",
    name: "Season 7.2.5",
    expansionId: ExpansionEnum.LEGION,
    startTime: new Date(0),
    endTime: new Date(1),
    affixId: null,
    seasonId: SeasonId.LEGION_7_2_5,
  },
  {
    slug: "legion-7.3.0",
    name: "Season 7.3",
    expansionId: ExpansionEnum.LEGION,
    startTime: new Date(0),
    endTime: new Date(1),
    affixId: null,
    seasonId: SeasonId.LEGION_7_3_0,
  },
  {
    slug: "legion-7.3.2",
    name: "Season 7.3.2",
    expansionId: ExpansionEnum.LEGION,
    startTime: new Date(0),
    endTime: new Date(1),
    affixId: null,
    seasonId: SeasonId.LEGION_7_3_2,
  },
  {
    slug: "legion-7.3.2-post",
    name: "Legion Post-Season",
    expansionId: ExpansionEnum.LEGION,
    startTime: new Date(0),
    endTime: new Date(1),
    affixId: null,
    seasonId: SeasonId.LEGION_POST_SEASON,
  },
  {
    slug: "legion-pre-bfa",
    name: "BFA Pre-Season",
    expansionId: ExpansionEnum.LEGION,
    startTime: new Date(0),
    endTime: new Date(1),
    affixId: null,
    seasonId: SeasonId.BFA_PRE_SEASON,
  },
  // BFA
  {
    slug: "bfa-1",
    name: "BFA Season 1",
    expansionId: ExpansionEnum.BATTLE_FOR_AZEROTH,
    startTime: new Date(0),
    endTime: new Date(1),
    affixId: getAffixByName("Infested"),
    seasonId: SeasonId.BFA_SEASON_1,
  },
  {
    slug: "bfa-2",
    name: "BFA Season 2",
    expansionId: ExpansionEnum.BATTLE_FOR_AZEROTH,
    startTime: new Date(0),
    endTime: new Date(1),
    affixId: getAffixByName("Reaping"),
    seasonId: SeasonId.BFA_SEASON_2,
  },
  {
    slug: "bfa-2-post",
    name: "BFA Post-Season 2",
    expansionId: ExpansionEnum.BATTLE_FOR_AZEROTH,
    startTime: new Date(0),
    endTime: new Date(1),
    affixId: getAffixByName("Reaping"),
    seasonId: SeasonId.BFA_POST_SEASON_2,
  },
  {
    slug: "bfa-3",
    name: "BFA Season 3",
    expansionId: ExpansionEnum.BATTLE_FOR_AZEROTH,
    startTime: new Date(0),
    endTime: new Date(1),
    affixId: getAffixByName("Beguiling"),
    seasonId: SeasonId.BFA_SEASON_3,
  },
  {
    slug: "bfa-3-post",
    name: "BFA Post-Season 3",
    expansionId: ExpansionEnum.BATTLE_FOR_AZEROTH,
    startTime: new Date(0),
    endTime: new Date(1),
    affixId: getAffixByName("Beguiling"),
    seasonId: SeasonId.BFA_POST_SEASON_3,
  },
  {
    slug: "bfa-4",
    name: "BFA Season 4",
    expansionId: ExpansionEnum.BATTLE_FOR_AZEROTH,
    startTime: new Date(0),
    endTime: new Date(1),
    affixId: getAffixByName("Awakened"),
    seasonId: SeasonId.BFA_SEASON_4,
  },
  {
    slug: "bfa-4-post",
    name: "BFA Post-Season 4",
    expansionId: ExpansionEnum.BATTLE_FOR_AZEROTH,
    startTime: new Date(0),
    endTime: new Date(1),
    affixId: getAffixByName("Awakened"),
    seasonId: SeasonId.BFA_POST_SEASON_4,
  },
  // SL
  {
    slug: "sl-1",
    name: "SL Season 1",
    expansionId: ExpansionEnum.SHADOWLANDS,
    startTime: new Date(1_607_385_600 * 1000),
    endTime: null,
    affixId: getAffixByName("Prideful"),
    seasonId: SeasonId.SL_SEASON_1,
  },
].map((dataset, index) => ({ ...dataset, id: index }));
