name: 💡 Feature Request
description: I want to add something to Keystone Heroes.
title: "[Feature]: "
labels:
  - feature
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing!

        Do you need some help?
        ======================
        The issue tracker is meant for feature requests and bug reports only. This isn't the best place for
        support or usage questions. Questions here don't have as much visibility as they do elsewhere. Before
        you ask a question, here are some resources to get help first:

        - Ask in GitHub Discussions: https://github.com/ljosberinn/keystone-heroes/discussions
        - Ask in chat: https://discord.gg/ubUjUTMdhE
  - type: textarea
    attributes:
      label: What is the new or updated feature that you are suggesting?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why should this feature be included?
    validations:
      required: true